config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

namespace :admin do
    get 'customers/search'
    resources :customers, only:[:index,:show,:edit,:update]
    resources :posts, except:[:new,:create]
    root to: 'homes#top'
  end

  scope module: :public do
    get 'posts/search'
    get 'posts/following_post'
    resources :posts do
      resources :post_comments, only: [:create, :destroy,:edit,:update]
      resource :likes, only: [:create, :destroy]
    end
    get 'customers/search'
    resources :customers, only:[:show,:edit,:index,:update] do
      member do
        get :follows, :followers,:likes
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:index, :destroy]
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :following, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_customer, through: :following, source: :follower # 自分がフォローしている人
  has_many :follower_customer, through: :follower, source: :following # 自分をフォローしている人
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image
  has_many_attached :post_images
  
  
  def follow(user_id)
    following.create(follower_id: user_id)
  end
  
  def unfollow(user_id)
    following.find_by(follower_id: user_id).destroy
  end
  
  def following?(user)
    following_customer.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end
  
  def create_notification_follow!(current_customer)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_customer.id, id, 'follow'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
    
  def bad_score?
    sum = posts.sum {|post| post.score.to_f}
    if sum < -1
      true
    else
      false
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.order(id: "DESC")
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.order(id: "DESC")
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_path
    else
      flash[:notice] = "入力内容を確認してください"
      render "edit"
    end
  end

  def search
    @customers = Customer.where("name LIKE ?" , "%#{params[:name]}%")
  end

  private

  def customer_params
    params.require(:customer).permit(
      :name,
      :email,
      :is_deleted
      )
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
 <div class="container">
  <div class="row">
    <div class="col-md-9">
      <h4><%= @customer.name %>さんの会員情報編集</h4>
      <%= form_with(model: @customer, url: admin_customer_path, local: true ,method: :patch) do |f| %>
      <table class="table table-borderless table-sm">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
          <td></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td scope="col", style="width: 50%"><%= f.text_field :name, autofocus: true %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
          <td></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td class="form-inline", style="font-size : 20px;">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_deleted, 'false' %><%= f.label :is_deleted, '有効', value: false %>
            </div>
            <div class="form-check form-check-inline">
              　<%= f.radio_button :is_deleted, 'true' %><%= f.label :is_deleted, '退会', value: true %>
            </div>
          </td>
          <td></td>
        </tr>
      </table><br>
      <div style="margin-left: 160px">
          <%= f.submit '変更を保存', class:"btn btn-outline-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-9">
    <%= form_with url: admin_customers_search_path, method: :get do |f| %>
          <%= f.label :顧客検索 %>
          <%= f.text_field :name %>
          <%= f.submit "検索" %>
      <% end %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">会員id</th>
            <th scope="col">氏名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">会員ステータス</th>
              <th scope="col">評価</span </th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted == false %>
                  <p class="text-success font-weight-bold">有効</p>
                <% else %>
                  <p class="text-secondary font-weight-bold">退会</p>
                <% end %>
            </td>
            <td>
    
              <% if customer.bad_score? %>
           　  　<div class="red-maru"></div>
           　　<%else%>
           　　 　<div class="green-maru"></div>
           　　<%end%>
             </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">会員id</th>
            <th scope="col">氏名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">会員ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted == false %>
                  <p class="text-success font-weight-bold">有効</p>
                <% else %>
                  <p class="text-secondary font-weight-bold">退会</p>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">  
  <div class="row">
    <div class="col-md-6">
      <h4>
        <%=link_to @customer.name, customer_path(@customer) %>さんの会員詳細
      </h4>
      <table class="table">
        <tr>
          <th>会員ID</th>
          <th><%= @customer.id %></th>
        </tr>
        <tr>
          <th>氏名</th>
          <th><%= @customer.name %></th>
        </tr>
         <tr>
        <tr>
          <th>メールアドレス</th>
          <th><%= @customer.email %></th>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <th><% if @customer.is_deleted == false %>
                 <p class="text-success">有効</p>
               <% else %>
                 <p class="text-secondary">退会</p>
               <% end %>
          </th>
        </tr>
         <tr>
           <td><%= link_to "編集する",edit_admin_customer_path(@customer), class:"btn btn-outline-secondary" %></td>
         </tr>
      </table>
    </div>
    <div class="col-md-6">
      <%= render 'admin/posts/index', posts: @posts %>
    </div>
  </div>
</div>