config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

namespace :admin do
    get 'customers/search'
    resources :customers, only:[:index,:show,:edit,:update]
    resources :posts, except:[:new,:create]
    root to: 'homes#top'
  end

  scope module: :public do
    get 'posts/search'
    get 'posts/following_post'
    resources :posts do
      resources :post_comments, only: [:create, :destroy,:edit,:update]
      resource :likes, only: [:create, :destroy]
    end
    get 'customers/search'
    resources :customers, only:[:show,:edit,:index,:update] do
      member do
        get :follows, :followers,:likes
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:index, :destroy]
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :name, presence: true, length: { minimum: 1, maximum: 35 }
  validates :ride_area, presence: true
  validates :title, presence: true, length: { minimum: 1, maximum: 180 }
  validates :body, presence: true, length: { minimum: 1, maximum: 450 }

  belongs_to :customer, optional: true

  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_customers, through: :likes, source: :customer
  has_many :notifications, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :replies, class_name: PostComment, foreign_key: :reply_comment, dependent: :destroy

  has_many_attached :post_images


  def liked_by?(customer)
    likes.exists?(customer_id: customer.id)
  end

  def create_notification_like(current_user)
    notification = current_user.active_notifications.new(
      post_comment_id: nil,
      post_id: id,
      visited_id: customer_id,
      action: 'like'
      )
    if notification.visitor_id == notification.visited_id
       notification.checked = true
    end
    notification.save if notification.valid?
  end

  def create_notification_comment(current_user, post_comment_id)
    # 自分以外で投稿にコメントしているユーザーを取得
    temp_ids = PostComment.select(:customer_id).where(post_id: id).where.not(customer_id: current_user).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, post_comment_id, temp_id['customer_id'])
    end
    save_notification_comment(current_user, post_comment_id, customer_id) if temp_ids.blank?
  end

  #(通知をした人,通知されたコメント,通知された人)
  def save_notification_comment(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


   enum ride_area:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @post = Post.find(params[:id])
    @post_comments = PostComment.all
  end
  
  def index
    @posts = Post.all.order(id: "DESC")
  end
  
  def edit
    @post = Post.find(params[:id])
    if admin_signed_in?
      render "edit"
    else
      redirect_to posts_path
    end
  end
  
  def update
    @post = Post.find(params[:id])
    @post.score = Language.get_data(post_params[:body])
    if @post.update(post_params)
      @post.post_images.each do |image|
         tags = Vision.get_image_data(image)
         tags.each do |tag|
           @post.tags.create(name: tag)
         end
       end
      redirect_to admin_post_path(@post), notice: "投稿を編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を消去しました"
  end
  
  private

  def post_params
    params.require(:post).permit(:name,:ride_area, :title, :body, post_images: [] )
  end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>投稿日</th>
      <th>温泉名</th>
      <th>評価</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td>
          <%= link_to admin_customer_path(post.customer) do%>
            <%= image_tag post.customer.get_profile_image(50,50) , class: "rounded-circle", size: "50x50" %><br>
            <%= post.customer.name %>
          <% end %>
        </td>
        <td>
          <%= l post.created_at, format: :short %>
        </td>
        <td>
          <%= link_to admin_post_path(post) do%>
            <%= post.name %>
          <% end %>
        </td>
        <td>
          <% if post.score >= 0.3 %>
            <i class="fa-regular fa-face-laugh-beam"></i>
          <% elsif post.score > -0.3 %>
            <i class="fa-regular fa-face-rolling-eyes"></i>
          <% else %>
            <i class="fa-regular fa-face-sad-tear"></i>
          <% end %>
        </td>
        <td><%= post.post_comments.count %>コメント</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/edit.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>投稿編集画面</h1>
      <%= form_with model:@post,url: admin_post_path(@post), method: :PATCH, remote:false do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
        <%= f.label :県名 %>
        <%= f.select :ride_area, Post.ride_areas.keys, {} %>
        </div>
        <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control' %>
        </div>
        <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :post_images, multiple: true, class: 'form-control' %>
        </div>
        <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "index", posts: @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-lg-6">
        <% if @post.post_images.attached? %>
          <div style="width: 500px;">
            <p><strong>投稿画像</strong></p>
            <% @post.post_images.each do |image| %>
              <%= image_tag image.variant(resize:'240x240').processed %>
            <% end %>
          </div>
        <% end %>
        <div　style="width: 25rem;">
          <div class="card-body">
            <h5 class="card-title">
              <%= image_tag @post.customer.get_profile_image(50,50) ,class:  "rounded-circle" %>
              <%= link_to @post.customer.name ,admin_customer_path(@post.customer)%><br>
            <% if @post.score >= 0.3 %>
              <i class="fa-regular fa-face-laugh-beam"></i>
            <% elsif @post.score > -0.3 %>
              <i class="fa-regular fa-face-rolling-eyes"></i>
            <% else %>
              <i class="fa-regular fa-face-sad-tear"></i>
            <% end %>
              <%= @post.name %>(<%= @post.ride_area%>)
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">~~<%= @post.title %>~~</h6>
            <p class="card-text"><%= @post.body %></p>
            <p class="text-right"><small>投稿日<%= l @post.created_at %></small></p>
            <% if admin_signed_in? %>
            <div class="text-right">
               <%= link_to '編集', edit_admin_post_path(@post), class: "btn btn-sm btn-success"%>
               <%= link_to '消去', admin_post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
            </div>
             <% end %>
          </div>
        </div>
        <div class="col-lg-6">
          <% if customer_signed_in? %>
          <div id="comments_form">
            <%= render partial: 'public/post_comments/form', locals:{ post: @post, post_comment: @post_comment } %>
          </div>
          <% end %>
          <h3>コメント一覧</h3>
          <div id="comments_area">
            <%= render partial: 'public/post_comments/index', locals:{post: @post,post_comments: @post_comments } %>
          </div>
        </div>
      </div>
  
    </div>
  </div>