config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

namespace :admin do
    get 'customers/search'
    resources :customers, only:[:index,:show,:edit,:update]
    resources :posts, except:[:new,:create]
    root to: 'homes#top'
  end

  scope module: :public do
    get 'posts/search'
    get 'posts/following_post'
    resources :posts do
      resources :post_comments, only: [:create, :destroy,:edit,:update]
      resource :likes, only: [:create, :destroy]
    end
    get 'customers/search'
    resources :customers, only:[:show,:edit,:index,:update] do
      member do
        get :follows, :followers,:likes
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:index, :destroy]
    root to: 'homes#top'
    get 'about' => 'homes#about'
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :following, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_customer, through: :following, source: :follower # 自分がフォローしている人
  has_many :follower_customer, through: :follower, source: :following # 自分をフォローしている人
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image
  has_many_attached :post_images
  
  
  def follow(user_id)
    following.create(follower_id: user_id)
  end
  
  def unfollow(user_id)
    following.find_by(follower_id: user_id).destroy
  end
  
  def following?(user)
    following_customer.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end
  
  def create_notification_follow!(current_customer)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_customer.id, id, 'follow'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
    
  def bad_score?
    sum = posts.sum {|post| post.score.to_f}
    if sum < -1
      true
    else
      false
    end
  end

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  
  validates :room_id, uniqueness: { scope: :customer_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  
  validates :body, presence: true, length: { minimum: 1, maximum: 256 }
  
  belongs_to :customer
  belongs_to :room
end

app/models/notification.rb
class Notification < ApplicationRecord
  
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true

  belongs_to :visitor, class_name: 'Customer', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'Customer', foreign_key: 'visited_id', optional: true
  
end

app/models/onsen.rb
class Onsen < ApplicationRecord
  
  belongs_to :customer
  has_many :onsen_tags, dependent: :destroy
  has_many :onsen_comments, dependent: :destroy
  
end

app/models/onsen_comment.rb
class OnsenComment < ApplicationRecord
end

app/models/onsen_tag.rb
class OnsenTag < ApplicationRecord
  belongs_to :onsen
  belongs_to :tag
end

app/models/post.rb
class Post < ApplicationRecord

  validates :name, presence: true, length: { minimum: 1, maximum: 35 }
  validates :ride_area, presence: true
  validates :title, presence: true, length: { minimum: 1, maximum: 180 }
  validates :body, presence: true, length: { minimum: 1, maximum: 450 }

  belongs_to :customer, optional: true

  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_customers, through: :likes, source: :customer
  has_many :notifications, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :replies, class_name: PostComment, foreign_key: :reply_comment, dependent: :destroy

  has_many_attached :post_images


  def liked_by?(customer)
    likes.exists?(customer_id: customer.id)
  end

  def create_notification_like(current_user)
    notification = current_user.active_notifications.new(
      post_comment_id: nil,
      post_id: id,
      visited_id: customer_id,
      action: 'like'
      )
    if notification.visitor_id == notification.visited_id
       notification.checked = true
    end
    notification.save if notification.valid?
  end

  def create_notification_comment(current_user, post_comment_id)
    # 自分以外で投稿にコメントしているユーザーを取得
    temp_ids = PostComment.select(:customer_id).where(post_id: id).where.not(customer_id: current_user).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, post_comment_id, temp_id['customer_id'])
    end
    save_notification_comment(current_user, post_comment_id, customer_id) if temp_ids.blank?
  end

  #(通知をした人,通知されたコメント,通知された人)
  def save_notification_comment(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


   enum ride_area:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  validates :comment, presence: true
  
  has_many :notifications, dependent: :destroy
  belongs_to :customer
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :following, class_name: "Customer"
  belongs_to :follower, class_name: "Customer"
  
end

app/models/room.rb
class Room < ApplicationRecord
  
 has_many :entries, dependent: :destroy
 has_many :messages, dependent: :destroy
 has_many :customers, through: :entries
 
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  belongs_to :post
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/onsens_helper.rb
module OnsensHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='w-auto '>
  <div class='row pt-3 bg-dark'>
  	<div class='mx-auto'>
  		<p class="text-white">©onsen.daisuki</p>
  	</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-xl navbar-dark bg-dark py-3">
    <a class="navbar-brand p-3" href="/">温泉投稿サイト</a>
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarCollapse-2" aria-controls="navbarCollapse-2" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse-2">
      <ul class="navbar-nav ml-auto mr-sm-2 mt-2 mt-lg-0">
        <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ" ,customer_path(current_customer), class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to "タイムライン",posts_path, class: 'nav-link'  %>
          </li>
          <li class="nav-item">
            <%= link_to "通知",notifications_path, class: 'nav-link'  %>
            <% if unchecked_notifications.any? %>
              <span class= "text-danger">●</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "いいね一覧",likes_customer_path(current_customer), class: 'nav-link'  %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿",new_post_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "DM",rooms_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to  "ログアウト",destroy_customer_session_path, method: :delete, class: 'nav-link', data: { confirm: 'ログアウトしますか？' } %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "投稿一覧", admin_posts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link', data: { confirm: 'ログアウトしますか？' } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Home",root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "サイト紹介",about_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録",new_customer_registration_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン",new_customer_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onsen-App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/4bdc1e604f.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "main">
      <div id="notice"><%= notice %></div>
      <div id="alert"><%= alert %></div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>